version: '3.9'

services:
  nginx:
    image: nginx:latest
    container_name: nginx
    ports:
      - "8085:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf:ro
    depends_on:
      - next_js

  next_js:
    container_name: next_js
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - NEXT_PUBLIC_APP_NAME=${NEXT_PUBLIC_APP_NAME}
        - NEXT_PUBLIC_VERSION=${NEXT_PUBLIC_VERSION}
        - NEXT_PUBLIC_API_URL=${NEXT_PUBLIC_API_URL}
    env_file:
      - .env
   
